version: "3.5"

services:
  deployscript:
    build: "./deployscript"
    image: "poundpython/infobob-docker-deploy"
    volumes:
      - type: bind
        source: /var/lib/infobob-gpg
        target: /run/gnupg
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: tmpfs
        target: /tmp
