version: "3.5"

services:
  znc:
    image: "znc:1.7-slim"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "25M"
        reservations:
          cpus: "0.1"
          memory: "25M"
    volumes:
      - "zncdata:/znc-data"

  infobob-master:
    image: "poundpython/infobob:branch-master"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: "200M"
        reservations:
          cpus: "0.5"
          memory: "125M"
    command:
      - "/run/secrets/infobob-master-config"
    secrets:
      - "infobob-master-config"
    volumes:
      - "infobob:/app"

  infobob-testing:
    image: "poundpython/infobob:branch-testing"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: "0"
        reservations:
          cpus: "0.1"
          memory: "0"
    command:
      - "/run/secrets/infobob-testing-config"
    secrets:
      - "infobob-testing-config"

  webhooks:
    image: "poundpython/webhooks"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.2"
          memory: "25M"
        reservations:
          cpus: "0.1"
          memory: "25M"
    command:
      - "/run/secrets/webhooks-env"
    secrets:
      - "webhooks-env"

  rproxy:
    image: "poundpython/rproxy"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: "75M"
        reservations:
          cpus: "0.1"
          memory: "50M"
    volumes:
      - "rproxy-certs:/usr/src/app/certs"
    configs:
      - source: rproxy-config
        target: "/usr/src/app/rproxy.ini"
    ports:
      - target: 8080
        published: 80
        protocol: tcp
        mode: host
      - target: 8443
        published: 443
        protocol: tcp
        mode: host

configs:
  rproxy-config:
    name: rproxy-ini-${HASHED_rproxy_ini}
    file: ./rproxy-prod.ini

secrets:
  infobob-master-config:
    name: infobob-master-config-${HASHED_infobob_master_config}
    external: true
  infobob-testing-config:
    name: infobob-testing-config-${HASHED_infobob_testing_config}
    external: true
  webhooks-env:
    name: webhooks-env-${HASHED_webhooks_env}
    external: true

volumes:
  infobob:
  rproxy-certs:
  zncdata:
